version: '3.7'
services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=initialDB
      - POSTGRES_USER=peta
      - POSTGRES_PASSWORD=98745